### PR TITLE
 #160577488 Users should be able to tag their articles

### PR DESCRIPTION
**Pull request by lukorito**
#### What does this PR do?
This PR creates a feature that will enable users to create tags when they are creating articles
#### Description of Task to be completed?
Have the following endpoints working
`GET api/tags` - Get all tags
`POST api/article` - Save tags with an article instance
#### How should this be manually tested?
**Prerequisites**
- Postgres SQL
- Postman

Procedure
- Clone the repository `https://github.com/andela/ah-shakas.git`
- Change your working directory to the project folder `cd ah-shakas`
- Checkout to the current branch `git checkout ft-articles-tags-160577488`
- Create a virtual environment using [pipenv](https://pipenv.readthedocs.io/en/latest/) `pipenv install` which will also install the dependencies
- Setup the environment variables as shown in `.env-example` and save it as `.env`
- Use `pipenv shell` on the terminal to access the virtualenvironment and all the variables will be exported
- Run the necessary migrations `python manage.py migrate`
- Run the tests `python manage.py test` to see the passing tests
- Run the Django server with `python manage.py runserver`
- Use [POSTMAN](https://www.getpostman.com/) or an API Development Environment of choice
- Sign up a user using the following payload format at `api/users/`:
```
{
	"user": {
		"username": "username",
		"email": "email@email.com",
		"password": "Password4"
	}
}
```
- Login the user using the above payload at `api/user/login` and you will receive a token
- Use the format `key: Authorization, value:Token` for the header
- Create an article by accessing `api/articles/` and sending a payload in the following format:
```
{
	"article" : {
		"title": "This is a title",
		"description": "This is a description",
		"body": "this is a body",
		"tags": ["sample","tags"]
	}
}
```
- Send a `GET` request to the article at the url`api/articles/{slug}` and the following response should be expected.
```
{
    "status": "success",
    "article": {
        "title": "This is a title",
        "description": "This is a description",
        "body": "this is a body",
        "slug": "this-is-a-title",
        "tags": [
            "sample",
            "tags"
        ],
        "image_url": null,
        "author": {
            "username": "username",
            "bio": "Update your bio",
            "image_url": "image-url",
            "following": false,
            "created_at": "2018-10-15T12:41:23.321669+03:00",
            "updated_at": "2018-10-15T12:41:23.326428+03:00"
        },
        "created_at": "2018-10-15T12:42:14.325535+03:00",
        "updated_at": "2018-10-15T12:42:14.325558+03:00"
    }
}
```
- To get a list of all Tags in the database, send a GET request at `api/tags/` and the following response is expected:
```
{
    "tags": [
        "sample",
         "tags"
    ]
}
```
#### Any background context you want to provide?
Tagging refers to the metadata that is assigned to a piece of content by the content creator and the readers/users of the content. Tagging allows for organization and or categorization of content.
#### What are the relevant pivotal tracker stories?
[160577488](https://www.pivotaltracker.com/story/show/160577488)
#### Screenshots (if appropriate)
**List of Tags**
screenshot 2018-10-14 01 46 28
**Article with Tags**
screenshot 2018-10-14 01 47 51

### CODE REVIEW

**Comment by koechkevin** [comment]
@lukorito in your PR include the required environment variables

**Review by codingedward — CHANGES_REQUESTED** [review]
Please work on slugifying your tags as well as checking on tags with the same name but different cases as we've agreed.

Otherwise, good job.

**Review by codingedward — APPROVED** [review]

**Comment by caveinn** [comment]
@lukorito I think it would be better if you added a prerequisite section under the part for manual testing so that whoever will be reviewing can know what they need such as the database and pipenv.  Because not everyone uses pipenv.

**Comment by lukorito** [comment]
> @lukorito I think it would be better if you added a prerequisite section under the part for manual testing so that whoever will be reviewing can know what they need such as the database and pipenv. Because not everyone uses pipenv.

Noted

**Review by michael-basweti — APPROVED** [review]
I have tasted your branch and you have great code formatting. Good.

**Comment by gloriaodipo** [comment]
Your PR is nicely done, but just one thing you could change. The part where you have included a link to your PT story id, could you just edit that to display the story id alone. Use this format in the markdown: 
[story id number](link obtained from pivotal tracker for the specific story)

**Comment by lukorito** [comment]
> just edit that to display the story id alone. Us

Cool

**Pull request merged**
