### PR TITLE
#160577496 implement highlighting for articles

### PR DESCRIPTION
**Pull request by caveinn**
#### What does this PR do?
Have the implementation for highlighting of article snippets

#### Description of Task to be completed?
- Create a highlight by hitting the `/api/articles/<slug>/higlight/` endpoint
- Update an highlight by hitting teh `/api/articles/<slug>/highlight/<id>` endpoint

#### How should this be manually tested?
prerequisites:
- Have postgres installed and running on localhost
- Have [pipenv](https://pipenv.readthedocs.io/en/latest/) installed

1. Clone this repo with the command:
  `git clone https://github.com/andela/ah-shakas.git`

2. Cd into the ah-shakas directory:
`cd ah-shakas`

3. Checkout to the branch ft-highlighting-160577496 with the command:
`git checkout ft-highlighting-160577496`

4. Create a database and export the database
`createdb testdb`
 
5. Create a `.env` file and add the following in it:
```
PAGE_SIZE=10
MAX_PAGE_SIZE=100
EMAIL_HOST=smtp.sendgrid.net
EMAIL_HOST_USER=shakas
EMAIL_HOST_PASSWORD=Shakas123
EMAIL_PORT=587
DB_NAME=testdb
PASSWORD_RESET=http://127.0.0.1:8000
```
6. Activate the pipenv
`pipenv shell`

7. Install the dependencies
`pipenv install`

8. Migrate the models to the db
`./manage.py migrate`

9. Run the server
`./manage.py runserver` 

#### From postman

- Create a user by sending a post request to the "/api/user/" end point with the data body ` {"username':"prefered name", "email":"validemail", "password":"password"}`
The return data will include a token which we will require for testing the "/api/articles/" endpoint

- To check that highlighting works you need to create articles by sending a post request to the
endpoint `/api/articles/`
with the payload:
```
{
	"article":{
		"title":"some title1",
		"body":"this is the body for to test pagination"
	}
}
```
since it requires authorization on the headers you have to add
 *key*: Authorization *value*:`<token from above registration>` 
*key*: Content-Type *value*: applicatio/json
Repeat this for 11 times to create 11 articles
Send GET request to "/api/articles/" endpoint 
The returned payload should have the first part as such:
```
{
    "status": "success",
    "article": {
        "title": "some title1",
        "description": "",
        "body": "this is the body for to test pagination",
        "slug": "some-title1",
        "tags": [],
        "image_url": null,
        "author": {
            "username": "ramon",
            "bio": "Update your bio",
            "image_url": "image-url",
            "isfollowing": [],
            "created_at": "2018-10-22T15:49:58.876905+03:00",
            "updated_at": "2018-10-22T15:49:58.879924+03:00"
        },
        "rating": {
            "avg_rating": null,
            "rating": null
        },
        "likes_count": 0,
        "dislikes_count": 0,
        "created_at": "2018-10-22T19:57:32.163127+03:00",
        "updated_at": "2018-10-22T19:57:32.163170+03:00",
        "favourited": false,
        "time_to_read": "1 min"
    }
}
```
- To test the highlighting end point send a post request to `/api/articles/some-title1/highlight/` "where some-title1 is the slug from title above" endpoint with the following payload 
```
{
	"highlight":{
		"snippet":"this is the",
		"index":0,
		"comment":"some other comment"
	}
}
```
the response should be something like this:
```
{
    "author": "ramon",
    "article": "title",
    "snippet": "this is the",
    "comment": "some other comment",
    "index": 0,
    "id": 1
}
```

- To edit the comment of the highlight you created send a put request to `/api/articles/some-title1/highlight/1` "where 1 is the id for the highlight"
```
{
	"highlight":{
		"snippet":"this is the",
		"index":0,
		"comment":"new comment"
	}
}
```
the response payload should be:
```
{
	"highlight":{
		"snippet":"this is the",
		"index":0,
		"comment":"new comment"
	}
}

```

#### What are the relevant pivotal tracker stories?
[#160577496](https://www.pivotaltracker.com/n/projects/2198533/stories/160577496)

### CODE REVIEW

**Comment by lukorito** [comment]
@caveinn and @Ramon3162 Great work on the PR. You could squash the commits

**Comment by caveinn** [comment]
@lukorito  am still updating the pull request I have a few issues am fixing

**Comment by lukorito** [comment]
@caveinn great work on the PR but sensitive information such as hosting and password should not be placed in public like the `.env` file

**Review by lukorito — APPROVED** [review]
I have tested this feature and it is working accordingly. All tests are passing too. It should be ready for a merge.

**Pull request merged**
