### PR TITLE
#160577497 comments should track edit history

### PR DESCRIPTION
**Pull request by koechkevin**
#### What does this PR do?
- have every comment track its edit history
#### Description of Task to be completed?
- Modify the following endpoints to include edit history in response body
```[GET/POST]: /api/articles/<sug>/comments/ ``` 
```[PUT/GET]: /api/articles/<slug>/comments/<comment_id>/```
## requirements
- This application uses PostgreSQL as database engine
- You will use [postman](https://www.getpostman.com/) or any api client to test the endpoints
- You will need python version 3
- you will use [pipenv](https://pipenv.readthedocs.io/en/latest/) to create and manage a virtual environment.
## procedure
- Clone the repository 
```https://github.com/andela/ah-shakas.git```
- Change directory to the project folder 
```cd ah-shakas```
- checkout to this branch 
```
git checkout ft-track-edit-history-160577497
```
- Setup the environment variables as shown in .env-example and save it as .env
- Create and activate virtual environment 
```pipenv install```
```pipenv shell```
- make necesary migrations
```python manage.py migrate```
- to run the tests
```python manage.py test```
- To start the server
```python manage.py runserver```
- Using postman or any API client you chose, register a user using the endpoint
```POST: api/users/``` with the payload in the format 
```
{
	"user": {
		"username": "username",
		"email": "email@email.com",
		"password": "Password4"
	}
}
```
 Note that you will be required to use a valid email so that you can activate the user.
- You will obtain a token by making a POST request to ```api/users/login/``` with the body payload in the format 
```
{
	"user": {
		"email": "email@email.com",
		"password": "Password4"
	}
}
```
- Create an article by providing the following body payload
```
{
	"article" : {
		"title": "This is a title",
		"description": "This is a description",
		"body": "this is a body",
		"tags": ["sample","tags"]
	}
}
```
and headers with the following variables
```
_key_:Authorization, _value_:Token you obtained from login.
```
to the endpoint ```GET:api/articles/```
- you will receive a response in the format
```
{
    "status": "success",
    "article": {
        "title": "This is a title",
        "description": "This is a description",
        "body": "this is a body",
        "slug": "this-is-a-second-title-1",
        "tags": [
            "sample",
            "tags"
        ],
        "image_url": null,
        "author": {
            "username": "kevin",
            "bio": "Update your bio",
            "image_url": "image-url",
            "isfollowing": [],
            "created_at": "2018-10-18T20:28:03.806486+03:00",
            "updated_at": "2018-10-18T20:28:03.808565+03:00"
        },
        "rating": {
            "avg_rating": null,
            "rating": null
        },
        "created_at": "2018-10-18T20:30:04.371761+03:00",
        "updated_at": "2018-10-18T20:30:04.371783+03:00",
        "favourited": false,
        "time_to_read": "1 min"
    }
}
```
- use the slug you received from the response to make a comment on the same article by making a post request to the endpoint ```/api/articles/<slug>/comments/``` with the body payload in the format.
```
{
	"comment": {
		"body": "my comment"	
	}
	
}
```
Note that you should provide authorizaton details
```
_key_:Authorization, _value_:Token you obtained from login.
```
- you should receive a response as below
```
{
    "id": 1,
    "body": "my comment",
    "created_at": "18 Oct 2018 17:37:25",
    "updated_at": "18 Oct 2018 17:37:25",
    "author": "kevin",
    "article": "This is a second title",
    "history": [],
    "reply_count": 0,
    "threads": []
}
```
- Update the comment using the endpoint 
```/api/articles/<slug>/comments/<id>/``` where slug is the article's slug and id is response from the response you received.
- This endpoint requires authorization and its body payload takes the form
```
{
	"comment": {
		"body": "I comment this"	
	}
	
}
```
- The response takes the format
```
{
    "id": 1,
    "body": "I comment this",
    "created_at": "18 Oct 2018 12:07:54",
    "updated_at": "18 Oct 2018 13:00:11",
    "author": "kevin",
    "article": "This is a second title",
    "history": [
        {
            "body": "my comment!",
            "created_at": "18 Oct 2018 17:37:25"
        }
    ],
    "reply_count": 0,
    "threads": []
}
```
#### Any background context you want to provide?
- This task was dependant on [this](https://www.pivotaltracker.com/story/show/160577482) story
#### What are the relevant pivotal tracker stories?
[# 160577497](https://www.pivotaltracker.com/story/show/160577497)
#### Screenshots (if appropriate)
- when you make successive edits, the response should look like this
screen shot 2018-10-18 at 20 58 37

### CODE REVIEW

**Comment by caveinn** [comment]
@koechkevin I would recommend you squash your commits. It will be helpful for us when rebasing and also it would be good practice. Awesome work otherwise.

**Comment by lukorito** [comment]
Hi @koechkevin Kindly specify the branch that I will be working from

**Comment by lukorito** [comment]
I have reviewed this PR and I think it is ready for a merge

**Review by codingedward — APPROVED** [review]
I have gone through the implementation and I believe this is ready for a merge.

**Pull request merged**
