### PR TITLE
#160577490 Articles should be searchable and filterable

### PR DESCRIPTION
**Pull request by codingedward**
#### What does this PR do?
- It adds search and filtering to articles endpoint
#### Description of Task to be completed?
- The following endpoints should be functional

| Method | Endpoint | Description |
| ------ | ------ | ------- |
| `GET` | `/api/articles/?tag={tag}` | Filters the articles with the given tag. |
| `GET` |  `/api/articles/?author={name}` | Filters with the author |
| `GET` |  `/api/articles/?title={title}` | Filters the articles with the given title |
| `GET` |  `/api/articles/?description={text}` | Filters with the given description |
| `GET` |  `/api/articles/?search={text}` | Searches the title, the author and the description |

#### How should this be manually tested?
- Clone the github repository `git clone https://github.com/andela/ah-shakas` on your machine

- Change your working directory to the project folder `cd ah-shakas`

- Create a `.env` with the following values

```
DB_NAME=
DB_PASSWORD=
DB_HOST=
DB_USER=
EMAIL_HOST=
EMAIL_HOST_USER=
EMAIL_HOST_PASSWORD=
EMAIL_PORT=
EMAIL_SENDER=
DB_NAME=
DB_USER=
DB_PASSWORD=
DB_HOST=
PASSWORD_RESET=
```

- Checkout to this PR's branch `git checkout ft-article-ratings-160577480`

- Create a virtual environment using [pipenv](https://pipenv.readthedocs.io/en/latest/) `pipenv shell`

 - Install dependencies `pipenv install`

- Run the tests `python manage.py test`

- To test with Postman, first run `python manage.py runserver` and use the endpoints highlighted above.

#### Any background context you want to provide?
Any user can search for articles, they do not need to be authenticated.

#### What are the relevant pivotal tracker stories?
[#160577481](https://www.pivotaltracker.com/n/projects/2198533/stories/160577481)

#### Screenshots (if appropriate)
*Sample filter (using author)*
screen shot 2018-10-19 at 18 35 32

*Sample search*
screen shot 2018-10-19 at 18 32 00

### CODE REVIEW

**Comment by lukorito** [comment]
@codingedward great work on you PR. Maybe you could specify the environmental variables in the .env_example that is yet to be merged with my PR

**Comment by codingedward** [comment]
Cool @lukorito, I will work on this.

**Comment by lukorito** [comment]
This PR is ready for a merge

**Review by lukorito — APPROVED** [review]
I think it is okay

**Comment by caveinn** [comment]
Approved

**Pull request merged**
