### PR TITLE
#160577474 JWT Authentication

### PR DESCRIPTION
**Pull request by gloriaodipo**
**What does this PR do?**
- Add JWT authentication.

**Description of Task to be completed**
- Users once registered via the registration endpoint, should receive JWT as a response to be required on all subsequent calls to all other endpoints that require authentication.

**What are the relevant pivotal tracker stories?**
[160577474](https://www.pivotaltracker.com/n/projects/2198533/stories/160577474)

**The screenshot below shows token returned after successful registration**
screen shot 2018-09-26 at 15 36 10

**Additional Comment:**
- I worked on this task in collaboration with @codingedward

### CODE REVIEW

**Comment by caveinn** [comment]
Looks good from my perspective. Keep it up.

**Comment by lukorito** [comment]
@gloriaodipo maybe you should not encode the primary key. What do you think? Since the username is unique

**Review by FawazFarid — COMMENTED** [review]
@gloriaodipo For this change to work I'm guessing I should merge #9 first right?

**Comment by gloriaodipo** [comment]
@FawazFarid yes, that's right.

**Comment by codingedward** [comment]
Having gone through the story description again, it seems this PR should also include Login code as well. 

Apologies for this, we will work on it.

**Comment by codingedward** [comment]
Hello, 
I have successfully integrated the login aspect of the story.

**Comment by FawazFarid** [comment]
Hey Glo, this is working fine, Just one more thing.....Can you add a test for this? In this case, test when a user signs up, a token is returned in the response.

**Review by FawazFarid — APPROVED** [review]

**Pull request merged**
